---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ printf "%s-claim" (include "es.fullname" .) }}
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.elasticsearch.storageSize | default "2Gi" | quote }}
