apiVersion: v1
kind: Service
metadata:
  name: {{ template "es.fullname" . }}
  labels:
    k8s-app: {{ template "es.fullname" . }}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Elasticsearch"
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: db
  selector:
    k8s-app: {{ template "es.fullname" . }}
