---
- name: install python
  hosts: all
  become: true
  gather_facts: False

  tasks:
    - name: Install python
      raw: (apt -y update && apt install -y python python-setuptools python-pip build-essential libssl-dev libffi-dev python-dev)
      changed_when: False
