version: '3.3'
services:
  post_db:
    image: mongo:${VER_DB}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_d
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${VER_UI}
    volumes:
      - .ui:/code
    command: ["puma", "--debug", "-w", "2"]
    ports:
      - ${PORT}:9292/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:${VER_POST}
    volumes:
      - .build:/code
    networks:
      - back_net
      - front_net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${VER_COMMENT}
    volumes:
      - .comment:/code
    command: ["puma", "--debug", "-w", "2"]
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  back_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.2.0/24
  front_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.1.0/24
